# Generated by Django 3.0.6 on 2020-06-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_editor', '0003_auto_20200611_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/css')),
            ],
        ),
    ]
